FreeCycle/Controllers/DonacionesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using FreeCycle.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Net.Mail;
using FreeCycle.ViewModels;

namespace FreeCycle.Controllers
{
    public class DonacionesController : Controller
    {
        private readonly DatabaseContext _context;

        public DonacionesController(DatabaseContext context)
        {
            _context = context;
        }

        public ActionResult OfrecerDonacion(int UsuarioId)
        {
            ViewBag.UsuarioId = UsuarioId;
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CrearOfrecimiento([Bind("UsuarioId,adress,estado,objeto")] OfrecerDonacion ofrecimiento)
        {
            int flag = 0;
            if (ModelState.IsValid)
            {
                _context.Add(ofrecimiento);
                await _context.SaveChangesAsync();
                return RedirectToAction("HomePage", "Home", new { flag = 4, UsuarioId = ofrecimiento.UsuarioId });
            }

            return View("OfrecerDonacion", ofrecimiento);
        }

        //Esto le envía el parámetro a la vista directamente???
        public ActionResult SolicitudDonacion(int UsuarioId)
        {
            ViewBag.UsuarioId = UsuarioId;
            return View();
        }

        //flag 3 para registro de solicitud de donación exitoso
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CrearSolicitud([Bind("UsuarioId,adress,objeto")] SolicitudDonacion solicitud)
        {
            int flag = 0;
            if (ModelState.IsValid)
            {
                _context.Add(solicitud);
                await _context.SaveChangesAsync();
                return RedirectToAction("HomePage", "Home", new { flag = 3, UsuarioId = solicitud.UsuarioId });
            }

            return View("SolicitudDonacion", solicitud);
        }

        public async Task<IActionResult> ListaDeSolicitudesDeDonaciones(int UsuarioId)
        {
            ViewBag.UsuarioId = UsuarioId;
            var databaseContext = _context.solicitudDonacion.Include(s => s.Usuario);
            return View(await databaseContext.ToListAsync());
        }

        public async Task<IActionResult> ListaDeOfrecerDonaciones(int UsuarioId)
        {
            ViewBag.UsuarioId = UsuarioId;
            var databaseContext = _context.ofrecerDonacion.Include(s => s.Usuario);
            return View(await databaseContext.ToListAsync());
        }


        public async Task<IActionResult> DetallesDeSolicitudesDeDonaciones(int? id, int UsuarioId)
        {
            if (id == null)
            {
                return NotFound();
            }
            ViewBag.UsuarioId = UsuarioId;
            var solicitudDonacion = await _context.solicitudDonacion
                .Include(s => s.Usuario)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (solicitudDonacion == null)
            {
                return NotFound();
            }

            if(UsuarioId == solicitudDonacion.UsuarioId)
            {
                return View("DetallesDeMiSolicitud",solicitudDonacion);
            }

            return View(solicitudDonacion);
        }

        public async Task<IActionResult> DetallesDeOfertasDeDonaciones(int? id, int UsuarioId)
        {
            if (id == null)
            {
                return NotFound();
            }
            ViewBag.UsuarioId = UsuarioId;
            var ofertaDonacion = await _context.ofrecerDonacion
                .Include(s => s.Usuario)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (ofertaDonacion == null)
            {
                return NotFound();
            }
            if (UsuarioId == ofertaDonacion.UsuarioId)
            {
                return View("DetallesDeMiOferta", ofertaDonacion);
            }

            return View(ofertaDonacion);
        }


        [HttpPost]
        public ActionResult DetallesDeSolicitudesDeDonaciones(string Email,int Id,string descripcion)
        {
            var Usuario = _context.Usuario.FirstOrDefault(user => user.Id == Id);
            Correos c = new Correos();
            if (Usuario != null && Email!=null)
            {
                string donante = Usuario.Email.ToString();
                string objeto = descripcion;         

                string to = Email;
                string subject = "Possible donor";

                //Mejorar este mensaje y ponerlo con HTML
                string body = "Hello, the user: " +donante +" is interested in donating you the request: "+objeto+ ", that you posted in our page, please send him an email him with the details to the place were you can deal the donation.";

                c.enviarCorreo(to,subject,body);
                
                ViewBag.Email = Email;
                return RedirectToAction("HomePage", "Home", new { flag = 5, UsuarioId = Usuario.Id, Usuario.Email });

            }
            else
            {
                //Enviar VB de usuario no registrado
            }
            return View();
        }

        [HttpPost]
        public ActionResult DetallesDeOfertasDeDonaciones(string Email, int Id, string descripcion)
        {
            var Usuario = _context.Usuario.FirstOrDefault(user => user.Id == Id);
            Correos c = new Correos();
            if (Usuario != null)
            {
                string solicitante = Usuario.Email.ToString();
                string objeto = descripcion;

                string to = Email;
                string subject = "Possible petitioner";

                //Mejorar este mensaje y ponerlo con HTML
                string body = "Hello, the user: " + solicitante + " is interested in taking your request: " + objeto + ", that you posted in our page, please send him an email him with the details to the place were you can deal the donation.";

                c.enviarCorreo(to, subject, body);

                return RedirectToAction("HomePage", "Home", new { flag = 5, UsuarioId = Usuario.Id, Usuario.Email });
            }
            else
            {
                //Enviar VB de usuario no registrado
            }
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> DetallesDeMiSolicitud(int Id, int UsuarioId)
        {
            var solicitudDonacion = _context.solicitudDonacion.FirstOrDefault(solicitud => solicitud.Id == Id);
            if (solicitudDonacion != null)
            {
                _context.Remove(solicitudDonacion);
                await _context.SaveChangesAsync();
                return RedirectToAction("HomePage", "Home", new { flag = 6, UsuarioId = UsuarioId});
            }

            return View();
        }


        [HttpPost]
        public async Task<IActionResult> DetallesDeMiOferta(int Id, int UsuarioId)
        {
            var ofertaDonacion = _context.ofrecerDonacion.FirstOrDefault(oferta => oferta.Id == Id);
            if (ofertaDonacion != null)
            {
                _context.Remove(ofertaDonacion);
                await _context.SaveChangesAsync();
                return RedirectToAction("HomePage", "Home", new { flag = 7, UsuarioId = UsuarioId });
            }

            return View();
        }


    }
}

FreeCycle/Controllers/EmpresasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FreeCycle.Models;

namespace FreeCycle.Controllers
{
    public class EmpresasController : Controller
    {
        private readonly DatabaseContext _context;

        public EmpresasController(DatabaseContext context)
        {
            _context = context;
        }

     
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,CompanyName,Password,PhoneNumber,Email,NIT")] Empresa empresa)
        {
            int flag;
            String temp = empresa.Email;
            var Empresa = _context.Empresa.FirstOrDefault(empresa => empresa.Email == temp);
            if(Empresa == null)
            {
                if (ModelState.IsValid)
                {
                    _context.Add(empresa);
                    await _context.SaveChangesAsync();
                    return RedirectToAction("GoToIndex", "Home", new { flag = 3 });
                }
            }
            flag = 0;
            ViewBag.flag = flag;
            return View(empresa);
        }

       
    }
}

FreeCycle/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using FreeCycle.Models;
using FreeCycle.ViewModels;

namespace FreeCycle.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly DatabaseContext _context;

        public HomeController(DatabaseContext context, ILogger<HomeController> logger)
        {
            _context = context;
            _logger = logger;
        }

        //Flag 0 para correo incorrecto 
        //Flag 1 para contraseña incorrecta
        //Flag 2 para inicio de sesión exitoso
        
        [HttpPost]
        public async Task<IActionResult> Validacion([Bind("Email,Password")] Validacion validacion)
        {
                int flag = 0;
                var Usuario = _context.Usuario.FirstOrDefault(user => user.Email == validacion.Email);
                if (Usuario != null)
                {
                    if (Usuario.Password == validacion.Password)
                    {
                        
                        return RedirectToAction("HomePage", new { flag = 2,UsuarioId=Usuario.Id});
                    }
                    flag = 1;
                 

                }
                else
                {
                    var Empresa = _context.Empresa.FirstOrDefault(empresa => empresa.Email == validacion.Email);
                    if (Empresa != null)
                    {
                        if (Empresa.Password == validacion.Password)
                        {
                            return RedirectToAction("HomePage", new { flag = 2 });
                        }
                        flag = 1;
                    }
                    
                }
                ViewBag.flag = flag;
                
                return View("InicioSesion", validacion);
        }

        public IActionResult Index()
        {
            return View();
        }


        //Le llega la flag para mostrar el mensaje de registro exitoso
        //Este sería el flag 3
        public IActionResult GoToIndex(int flag)
        {
            ViewBag.flag = flag;
            return View("InicioSesion");
        }

        public IActionResult InicioSesion()
        {
            return View();
        }

        

        public IActionResult HomePage(int flag , int UsuarioId, string Email)
        {
            if(UsuarioId != 0 )
            {
                ViewBag.flag = flag;
                ViewBag.UsuarioId = UsuarioId;
                ViewBag.Email = Email;
                return View();
            }
            ViewBag.flag = 8;
            return View("InicioSesion");
        }

        public IActionResult Privacy()
        {
            return View();
        }

    }
}

FreeCycle/Views/Home/HomePage.cshtml
@{
    ViewData["Title"] = "Home Page";
}

@if (ViewBag.flag == 2)
{
    <div class="alert alert-success" role="alert">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <strong>
            Successful login
        </strong>
    </div>
}
@if (ViewBag.flag == 3)
{
    <div class="alert alert-success" role="alert">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <strong>
            Donation request successfully registered
        </strong>
    </div>
}
@if (ViewBag.flag == 4)
{
    <div class="alert alert-success" role="alert">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <strong>
            Donation offer successfully registered
        </strong>
    </div>
}
@if (ViewBag.flag == 5)
{
    <div class="alert alert-success" role="alert">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <strong>
            An Email with your info has been sent to "@ViewBag.Email" succesfully, please wait until he emails you to deal the donation.
        </strong>
    </div>
}
@if (ViewBag.flag == 6)
{
    <div class="alert alert-success" role="alert">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <strong>
            Your request has been deleted succesfully.
        </strong>
    </div>
}
@if (ViewBag.flag == 7)
{
    <div class="alert alert-success" role="alert">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <strong>
            Your offer has been deleted succesfully.
        </strong>
    </div>
}

<div class="text-center"><img src="/Imagenes/FreeCycle.png" class="rounded-circle" height="162" width="377" /></div>


<br />

<div class="text-center">

    <br />

    <div class="row">
        <div class="col-1">

        </div>
        <div class="col-5">
            <a asp-controller="Donaciones" asp-action="SolicitudDonacion" asp-route-UsuarioId="@ViewBag.UsuarioId" class="btn btn-info text-white btn-lg btn-block">Ask for a Donation</a>
        </div>
        <div class="col-5">
            <a asp-controller="Donaciones" asp-action="ListaDeOfrecerDonaciones" asp-route-UsuarioId="@ViewBag.UsuarioId" class="btn btn-info text-white btn-lg btn-block">Take a Donation</a>
        </div>

        <div class="col-1">

        </div>
    </div>

    <br />


    <br />

    <div class="row">
        <div class="col-1">

        </div>
        <div class="col-5">
            <a asp-controller="Donaciones" asp-action="OfrecerDonacion" asp-route-UsuarioId="@ViewBag.UsuarioId" class="btn btn-info text-white btn-lg btn-block">Offer a Donation</a>
        </div>
        <div class="col-5">
            <a asp-controller="Donaciones" asp-action="ListaDeSolicitudesDeDonaciones" asp-route-UsuarioId="@ViewBag.UsuarioId" class="btn btn-info text-white btn-block btn-lg">Make a Donation</a>
        </div>
        <div class="col-1">

        </div>
    </div>

</div>

<script type="text/javascript">
    setTimeout(function () {
        // Closing the alert
        $(".alert-success").fadeTo(1500, 500).slideUp(500, function () {
            $(".alert-success").slideUp(500);
        });
        $(".alert-warning").fadeTo(1500, 500).slideUp(500, function () {
            $(".alert-warning").slideUp(500);
        });
        $(".alert-danger").fadeTo(1500, 500).slideUp(500, function () {
            $(".alert-danger").slideUp(500);
        });
    }, 600);
</script>

FreeCycle/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<main role="main">

    <div class="text-center">
        <img src="/Imagenes/FreeCycle.png" class="rounded-circle" height="162" width="377" />
    </div>

    <div class="text-center">
        <h1 class="display-4">Welcome!</h1>
    </div>

    <br/>

    <div class="jumbotron">
        <div class="container">
            <div class="row">
                <div class="col-md-6">
                    <p style="text-align: justify">
                        In FreeCycle, we want you to connect with other people that have similar needs.<br />
                        Have you ever wanted to donate something that you don't use anymore?, however you don't know who might want it or maybe your situation is different and you're looking for something, but before wasting money on it, you wonder if someone could have that item and is looking to donate it?. <br />
                    </p>
                    <img src="/Imagenes/Donacion.png" height="100" width="500" />
                </div>
                <div class="col-md-6">
                    <p style="text-align: justify">
                        If that's your case we introduce you FreeCycle, a website where you can post your donation offers or your donation requests, all we need is your location, the item description and if you're offering, the status of the item, so people that are looking to take that offer or donating your request can easily deal the donation.
                        <br />
                        <br />
                        Let's get started!
                        <br />
                        <br />
                    </p>
                    <div class="text-center">
                        <p><a class="btn btn-info text-white btn-lg btn-block" href="/Home/InicioSesion" role="button">Sign In &raquo;</a></p>
                    </div>                  
                </div>
            </div>
        </div> <!-- /container -->  
    </div>

</main>

FreeCycle/Views/Home/InicioSesion.cshtml
@model FreeCycle.ViewModels.Validacion
@{
    ViewData["Title"] = "Sign in";
}


@if (ViewBag.flag == 0)
{
    <div class="alert alert-warning alert-dismissable">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <strong>Wrong Email</strong>
    </div>
}
@if (ViewBag.flag == 1)
{
    <div class="alert alert-warning alert-dismissable">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <strong>Wrong password</strong>
    </div>
}
@if (ViewBag.flag == 3)
{
    <div class="alert alert-success" role="alert">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <strong>Succesfully registered</strong>
    </div>
}
@if (ViewBag.flag == 4)
{
    <div class="alert alert-success" role="alert">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <strong>Successful password change</strong>
    </div>
}
@if (ViewBag.flag == 8)
{
    <div class="alert alert-warning alert-dismissible">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <strong>Please sign in first</strong>
    </div>
}


<div class="text-center">
    <h2 class="display-4">Sign in</h2>
    <hr />
    <br />

    <form asp-action="Validacion">
        <div class="form-group row">
            <div class="col-4"></div>
            <div class="col-4 ">

                <input asp-for="Email" type="email" class="form-control" placeholder="Email" />
                <span class="text-danger" asp-validation-for="Email"></span>

            </div>

        </div>
        <div class="form-group row">


            <div class="col-4"></div>
            <div class="col-4">
                <input asp-for="Password" type="password" class="form-control" placeholder="Password" />
                <span class="text-danger" asp-validation-for="Password"></span>
            </div>

        </div>



        <div class="row">
            <div class="col-4"></div>
            <div class="col-4">
                <input type="submit" class="btn btn-info text-white btn-block" value="Sign In" />
            </div>
        </div>

    </form>



    <a asp-controller="Usuarios" asp-action="RecuperarContraseña" class="form-text text-muted">Forgot your password?</a>

    <br />
    <div class="row">
        <div class="col-4"></div>
        <div class="col-4">
            <a asp-controller="Usuarios" asp-action="Create" class="btn btn-info text-white btn-block">Sign up as a Person</a>
        </div>
    </div>
    <br />
    <div class="row">
        <div class="col-4"></div>
        <div class="col-4">
            <a asp-controller="Empresas" asp-action="Create" class="btn btn-info text-white btn-block">Sign up as a Company</a>

        </div>
    </div>



</div>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

<script type="text/javascript">
    setTimeout(function () {
        // Closing the alert
        $(".alert-success").fadeTo(1500, 500).slideUp(500, function () {
            $(".alert-success").slideUp(500);
        });
        $(".alert-warning").fadeTo(1500, 500).slideUp(500, function () {
            $(".alert-warning").slideUp(500);
        });
        $(".alert-danger").fadeTo(1500, 500).slideUp(500, function () {
            $(".alert-danger").slideUp(500);
        });
    }, 600);
</script>